### PR TITLE
Detect nvm path when installed via brew

### PR DESCRIPTION
**Pull request by pkuczynski**

### CODE REVIEW

**Comment by wbyoung** [comment]
As far as I know, installation of `nvm` with Homebrew is not supported. Has this changed, @ljharb?

**Comment by pkuczynski** [comment]
I do not think this changed, but it does not mean that people are not doing it :)

**Comment by ljharb** [comment]
It has decidedly not changed; people are still doing it; and any tool that makes life short-term easier for people doing it is making their life long-term harder - they should be encouraged as strongly as possible to not use homebrew for nvm.

**Comment by wbyoung** [comment]
Agreeing with@ljharb and closing.

**Pull request closed without merging**
